
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    volumes: 
      - postgres_volume:/var/lib/postgresql/data
    network_mode: host
volumes:
  postgres_volume:
    driver: local

# postgresql://postgres:postgres@localhost:5432/mydb