version: '2'
services:
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"