version: "3"
services:
  haproxy:
    image: haproxy:2.0.0
    container_name: haproxy
    ports:
      - "80:8100"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8082:80"

  webserver:
    image: httpd:alpine
    container_name: webserver
    restart: always
    ports:
      - "8081:80"

