version: '3'
services:  
  nginx:
    build: ./
    ports:
      - "9000:9000"
 
  octant:
    image: vcr.vngcloud.vn/60108-annd2-ingress/octant:v0.25.1
    container_name: octant-container
    environment:
      - "OCTANT_DISABLE_OPEN_BROWSER=true"
      - "OCTANT_LISTENER_ADDR=0.0.0.0:9000"
      - "KUBECONFIG=/output/kubeconfig.yaml"
    volumes:
      - "~/.kube/config:/output/kubeconfig.yaml"
    restart: always