version: "3.4"
services:
  squid:
    image: sameersbn/squid:3.5.27-2    
    restart: always
    container_name: squid
    hostname: squid
    volumes:
     - ./squid.conf:/etc/squid/squid.conf
     - ./hosts:/etc/hosts
    ports:
     - "3128:3128"