version: '2'
services:  
  mysql:
    image: mysql:latest
    container_name: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '6603:3306'
    volumes:
      # - ./my.cnf:/etc/mysql/my.cnf
      - ./custom:/etc/mysql/conf.d
      - mysql_volume:/var/lib/mysql
volumes:
  mysql_volume: