receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp:
    endpoint: "jaeger:4318"
    tls:
      insecure: true

  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4
    # endpoint: http://clickhouse:8123
    username: annd2
    password: password
    database: otel
    ttl_days: 3

    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse, otlp]
